### ISSUE TITLE
Missing historical MPI-ESM1-2-HR data

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/cmip6-utils#38]
It looks like historical MPI-ESM1-2-HR data is only available under MPI-M institution ID, which is different from the DKRZ where the ScenarioMIP data is found. Will need a way to handle this in the transfers pipeline.

**Comment by Joshdpaul** [comment]
The historical data and ScenarioMIP data for this model can be transferred under their respective institution IDs (`MPI-M` and `DKRZ`) and will be mirrored like that in order to match the structure of the upstream data. However, we need to make sure these data are combined in the regridding pipeline, since that data is organized by model ID and not institution ID. Check the regridding pipeline to make sure the process does not fail due to the differing institution IDs.
